require "haikunator/version"
require "securerandom"

module Haikunator
  class << self
    def haikunate(token_range = 9999, delimiter = "-")
      build(token_range, delimiter)
    end

    private

    def build(token_range, delimiter)
      sections = [
        adjectives[random_seed % adjectives.length],
        nouns[random_seed % nouns.length],
        token(token_range)
      ]

      sections.compact.join(delimiter)
    end

    def random_seed
      SecureRandom.random_number(4096)
    end

    def token(range)
      SecureRandom.random_number(range) if range > 0
    end

    def adjectives
      %w[
        abundant
        accomplished
        adorable
        adventurous
        affectionate
        agile
        alluring
        amazing
        ambitious
        ambrosial
        amethyst
        amiable
        ancient
        appreciative
        artistic
        astonishing
        attentive
        authentic
        autumn
        awesome
        balanced
        beautiful
        benevolent
        billowing
        bitter
        black
        blessed
        blissful
        blithe
        blue
        bold
        bountiful
        brave
        breathtaking
        bright
        brilliant
        buoyant
        calm
        captivating
        caring
        celebrated
        celestial
        charismatic
        charming
        cheerful
        chic
        classy
        clever
        cold
        collaborative
        comforting
        compassionate
        competent
        confident
        considerate
        cool
        courageous
        creative
        crimson
        crystal
        crystalline
        cultured
        curious
        damp
        dapper
        dark
        dashing
        dawn
        dazzling
        dedicated
        delicate
        delightful
        dependable
        determined
        devoted
        diaphanous
        diligent
        disciplined
        diurnal
        divine
        dry
        dulcet
        dynamic
        eager
        earnest
        ecstatic
        effervescent
        efficient
        effulgent
        elegant
        eloquent
        elysian
        empathetic
        empty
        empyreal
        enchanting
        energetic
        engaging
        enterprising
        enthusiastic
        ethereal
        euphoric
        excellent
        exciting
        exhilarating
        experienced
        expressive
        exquisite
        extraordinary
        exuberant
        fabulous
        faithful
        falling
        fantastic
        fascinating
        fashionable
        fearless
        feisty
        fierce
        flexible
        floral
        flourishing
        fortunate
        fragrant
        friendly
        frosty
        generous
        gentle
        genuine
        gleaming
        glorious
        glowing
        golden
        goldenrod
        gossamer
        graceful
        gracious
        great
        green
        halcyon
        handsome
        happy
        harmonious
        healthy
        heartwarming
        heavenly
        helpful
        heroic
        hidden
        holy
        honest
        honorable
        humble
        hushed
        icy
        imaginative
        impressive
        incandescent
        inclusive
        incredible
        independent
        ineffable
        ingenious
        innovative
        inquisitive
        insightful
        inspiring
        intelligent
        intuitive
        invigorating
        invincible
        iridescent
        jocund
        joyful
        joyous
        jubilant
        kind
        kindhearted
        knowledgeable
        late
        levitating
        lighthearted
        limitless
        lingering
        little
        lively
        long
        lovely
        loving
        loyal
        lucky
        luminiferous
        luminous
        lustrous
        magnetic
        majestic
        marvelous
        mature
        mellifluent
        mellifluous
        mellisonant
        mellow
        melodic
        mirthful
        misty
        morning
        motivated
        muddy
        mystic
        nameless
        nebulaic
        nebular
        nebulous
        nurturing
        old
        opalescent
        optimistic
        opulent
        organized
        outstanding
        passionate
        patient
        peaceful
        persistent
        playful
        polished
        polite
        positive
        precious
        productive
        professional
        progressive
        proud
        pure
        purple
        quiet
        quixotic
        radiant
        red
        reliable
        resilient
        resourceful
        respectful
        resplendent
        restless
        rough
        salty
        sapphire
        selfless
        sensible
        serendipitous
        serene
        shy
        silent
        silken
        sincere
        skillful
        small
        smooth
        snowy
        sociable
        solitary
        sonorous
        sparkling
        spiritual
        splendid
        spring
        still
        strong
        summer
        superb
        supportive
        svelte
        talented
        tenacious
        tender
        thoughtful
        thrumming
        timeless
        tranquil
        transformative
        trustworthy
        twilight
        unique
        uplifting
        urban
        valiant
        velveteen
        velvety
        vibrant
        victorious
        visionary
        vivacious
        vivid
        wandering
        weathered
        whispering
        white
        wild
        winter
        wise
        wispy
        withered
        witty
        wonderful
        young
        zealous
        zephyrian
        zephyrous
        zesty
      ]
    end

    def nouns
      %w[
        abundance
        acai
        accolade
        achievement
        adventure
        aptitude
        ascension
        aurora
        awakening
        balance
        beach
        beauty
        benevolence
        bird
        biscuit
        blessing
        bliss
        blooming
        blossom
        breeze
        brilliance
        brook
        bush
        butterfly
        buzz
        cachet
        camel
        captivation
        caress
        cascade
        celebration
        charisma
        cherry
        chime
        chocolate
        clarity
        cloud
        coffee
        collaboration
        compassion
        connectivity
        contentment
        cookie
        courage
        creativity
        curiosity
        dandelion
        darkness
        dawn
        deer
        delicacy
        delight
        desert
        determination
        dew
        diapason
        diorama
        discovery
        dream
        dust
        earth
        elation
        elevation
        elixir
        eloquence
        embrace
        empathy
        enchantment
        enclave
        encouragement
        endurance
        energy
        enlightenment
        enrichment
        enthusiasm
        entrancement
        ephemera
        epiphany
        epitome
        essence
        eternity
        ethereal
        ethereality
        euphoria
        excitement
        exhilaration
        exploration
        extraordinaire
        extravaganza
        exultation
        faith
        feast
        feather
        field
        fire
        firefly
        flamingo
        flourish
        flower
        fog
        forest
        forgiveness
        fox
        friend
        friendship
        frog
        frost
        fulfillment
        galaxy
        generosity
        gift
        glade
        glitter
        goodness
        gossamer
        grace
        grass
        gratefulness
        gratitude
        growth
        happiness
        harmony
        haven
        haze
        healing
        hearth
        hill
        honesty
        honey
        hope
        illumination
        imagination
        immersion
        impression
        incandescence
        indulgence
        ineffability
        infinity
        infusion
        innovation
        inspiration
        integrity
        island
        joy
        joyfulness
        jubilation
        jubilee
        jungle
        kindness
        kindred
        knowledge
        koala
        labyrinth
        lagoon
        lake
        laughter
        lavishness
        leaf
        legacy
        lilt
        log
        love
        lullaby
        luminance
        luminary
        luminescence
        lushness
        luxuriance
        magic
        marvel
        meadow
        meander
        mellifluousness
        mellowness
        melody
        mindfulness
        miracle
        momentum
        moon
        morning
        motivation
        mountain
        muse
        music
        nebula
        night
        nirvana
        nourishment
        oasis
        ocean
        optimism
        opulence
        otter
        owl
        painting
        panache
        pancake
        paper
        paradigm
        passion
        patience
        peace
        perfection
        perseverance
        petal
        phenomenon
        pine
        pinnacle
        pizzazz
        plains
        platypus
        playfulness
        pond
        pop
        positivity
        presence
        progress
        prosperity
        quiescence
        quintessence
        radiance
        rain
        rainbow
        reflection
        refreshment
        regeneration
        rejuvenation
        relish
        renewal
        resilience
        resonance
        restoration
        retreat
        revelation
        reverence
        revitalization
        rhapsody
        river
        sanctuary
        satisfaction
        savor
        sea
        sensation
        seraphim
        serenade
        serendipity
        serenity
        shadow
        shape
        silence
        sky
        smile
        smoke
        smoothie
        snail
        snow
        snowflake
        soaring
        sound
        soup
        sparkle
        spirit
        splendor
        sprinkles
        star
        stillness
        success
        sun
        sunset
        supernova
        support
        supremacy
        surf
        sweetness
        sylvan
        symphony
        synergy
        talent
        tapestry
        tea
        tempest
        tenacity
        thrill
        thunder
        tiramisu
        tranquility
        transcendence
        transformation
        treasure
        tree
        triumph
        tryst
        understanding
        unity
        upliftment
        utopia
        valley
        vegemite
        vellichor
        venture
        verdancy
        vibrance
        victory
        violet
        vision
        vitality
        vivacity
        voice
        wallaby
        wanderlust
        warmth
        water
        waterfall
        wave
        whimsey
        whimsy
        whirl
        whisper
        whiz
        wholeness
        wildflower
        wind
        wisdom
        wonder
        wonderment
        yearning
        zeal
        zephyr
        zest
        zing
      ]
    end
  end
end
